# Caldero Solver

## Formula

Deonte by $d$ the number of diplomas you have
$$
\begin{align*}
E_i(\alpha) & = \max\left\{\sum_{j=1}^{12}\alpha_j v_{i,j},0\right\}
\; 1.1^{\sum_{j=1}^{12}\alpha_j b_{i,j}},\\
\hat{E}_i(\alpha)&= 20\,\frac{E_i(\alpha)}{\sum_{k=1}^{21}E_k(\alpha)}\sqrt{\sum_{j=1}^{12}\alpha_j},\\
F(\alpha)&=\sum_{i=1}^{d} w_i\,\hat{E}_i(\alpha),
\end{align*}
$$
where $W=(v_{i,j}),B=(b_{i,j})\in\mathbb{R}^{d\times 12}$ are constant values, $w=(w_i)\in[0,1]^d$ is the weights(interest) in the $i$-effect. and $\alpha \in \{\alpha \in \mathbb{Z}_{26}: |\alpha|\leq 25\}$ are the number of ingredients. 

In [1]:
import numpy as np
from caldero_optimizer import CalderoOptimizer

## Parameters

In [2]:
n_dipl  = 18
n_ingr = CalderoOptimizer.n_ingr
premium_ingr = [3, 6, 8, 10]  # indices forced to zero
effect_weights = np.array([0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,1,0])
alpha_UB = np.full(n_ingr, 25, dtype=int)
prob_UB = np.full(n_dipl , 30, dtype=int)

In [3]:
opt = CalderoOptimizer(
    effect_weights=effect_weights,
    premium_ingr=premium_ingr,
    alpha_UB=alpha_UB,
    prob_UB=prob_UB,
)

# multi-start greedy
alpha_best, val_best = opt.multistart(n_starts=100)
print("\nBest over multi-start:")
print(alpha_best.reshape(3, 4))
print(f"Mean eefect prob: {val_best:.2f}%",)


Best over multi-start:
[[ 0  1 14  0]
 [ 0  3  0  0]
 [ 0  5  0  2]]
Mean eefect prob: 14.05%


## Probabilities on desired effects

In [4]:
(opt.effect_probabilities(alpha_best)*(effect_weights!=0)).round(2)

array([ 0.  ,  0.  , 29.51,  0.  ,  0.  ,  0.  ,  1.97,  0.  ,  0.  ,
        0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , 29.17,  9.6 ,  0.  ])

In [5]:
(opt.effect_probabilities(alpha_best)*(effect_weights!=0)).round(2)

array([ 0.  ,  0.  , 29.51,  0.  ,  0.  ,  0.  ,  1.97,  0.  ,  0.  ,
        0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , 29.17,  9.6 ,  0.  ])

In [ ]:
["Espora Ignea",
 "Escarabanuez",
 "Cascaron de Mana",
 "Iris Volador",
 "Huevo de Medusa",
 "Lima de Oruga",
 "Flor de hierba mora",
 "Lenguas burlonas",
 "Brote ocular",
 "hoja de agricabello",
 "capullo de nube de algodon",
 "trufa orejera"
 ]