# Caldero Solver

## Formula

Deonte by $d$ the number of diplomas you have
$$
\begin{align*}
E_i(\alpha) & = \max\left\{\sum_{j=1}^{12}\alpha_j v_{i,j},0\right\}
\; 1.1^{\sum_{j=1}^{12}\alpha_j b_{i,j}},\\
\hat{E}_i(\alpha)&= 20\,\frac{E_i(\alpha)}{\sum_{k=1}^{21}E_k(\alpha)}\sqrt{\sum_{j=1}^{12}\alpha_j},\\
F(\alpha)&=\sum_{i=1}^{d} w_i\,\hat{E}_i(\alpha),
\end{align*}
$$
where $W=(v_{i,j}),B=(b_{i,j})\in\mathbb{R}^{d\times 12}$ are constant values, $w=(w_i)\in[0,1]^d$ is the weights(interest) in the $i$-effect. and $\alpha \in \{\alpha \in \mathbb{Z}_{26}: |\alpha|\leq 25\}$ are the number of ingredients. 

In [1]:
import numpy as np
from cauldron_optimizer import CauldronOptimizer

## Parameters

In [2]:
n_dipl  = 24
n_ingr = CauldronOptimizer.n_ingredients
premium_ingr = [3, 6, 8, 10]  # indices forced to zero
effect_weights = np.array([0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0])
alpha_UB =  25
prob_UB = 30

In [3]:
opt = CauldronOptimizer(
    effect_weights=effect_weights,
    premium_ingr=premium_ingr,
    alpha_UB=alpha_UB,
    prob_UB=prob_UB,
)

# multi-start greedy
alpha_best, val_best = opt.multistart(n_starts=100)
print("\nBest over multi-start:")
print(alpha_best.reshape(3, 4))
print(f"Mean eefect prob: {val_best:.2f}%",)


Best over multi-start:
[[ 0  0 11  0]
 [ 0  5  0  0]
 [ 0  6  0  3]]
Mean eefect prob: 10.94%


## Probabilities on desired effects

In [4]:
(opt.effect_probabilities(alpha_best)*(effect_weights!=0)).round(2)

array([ 0.  ,  0.  , 29.31,  0.  ,  0.  ,  0.  ,  0.61,  0.  ,  0.  ,
        0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , 19.54,  5.27,  0.  ,
        0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ])

In [5]:
(opt.effect_probabilities(alpha_best)*(effect_weights!=0)).round(2)

array([ 0.  ,  0.  , 29.31,  0.  ,  0.  ,  0.  ,  0.61,  0.  ,  0.  ,
        0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , 19.54,  5.27,  0.  ,
        0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ])

In [6]:
opt.effect_probabilities(alpha_best)

array([ 1.10781324,  0.45857657, 29.30820186,  2.97357383,  1.58036023,
        3.13880417,  0.60929728,  0.        ,  0.        ,  2.79970455,
        0.        ,  1.04221949,  7.91565353,  0.        ,  0.        ,
       19.53879273,  5.26786743,  0.        ,  0.        ,  4.66617424,
        5.53906619, 12.64288182,  1.22955898,  0.18145386])